site_name: Портфолио технического писателя
site_description: "Как я создаю документацию: от инструкций до стайлгайдов. Портфолио с примерами работ."
theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
nav:
  - Главная: index.md
  - Обо мне: about.md
  - Принципы моей работы: how-i-work.md
  - Проверка AML:
    - AML-check: aml/aml-check.md
    - Интерпретация результатов проверки: aml/risk-interpretation.md
    - Уровни результатов проверки: aml/risk-levels.md
  - Сервис уведомлений:
    - О проекте: notification-service/index.md
    - Отправка email: notification-service/send-email-endpoint.md
    - Проверка статуса: notification-service/get-status-endpoint.md
    - Схема процесса: notification-service/notification-flow.md
  - База знаний для службы поддержки: 
    - Быстрое решение: support-kb/index.md
    - Схема процесса: support-kb/incident-flow.md
  - Стайлгайд:
    - Введение: style-guide/index.md
    - Оформление текста: style-guide/text-format.md
    - Язык и термины: style-guide/language-terms.md
markdown_extensions:
  - admonition
  - tables
  - fenced_code
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - extra-styles-v1.css
